### ISSUE TITLE
楼主好，我贪婪的小心脏想提一点建议

### ISSUE THREAD

**Issue by oknixus** [ForoneTech/ForoneAdmin#3]
您这个做的真的很好，界面也很漂亮，但是布局上，感觉不是很好！
现在只有一个权限管理的，就已经占掉了很大的页面空间，如果想做其他的功能进去，就挺不方便的

一点拙见，望海涵

**Comment by mani95lisa** [comment]
@NixusCN 这个是可以折叠的，所以问题不大，不展开一级菜单可以放很多东西的

**Comment by oknixus** [comment]
还想请教一下，这里有一个问题，就是看了您的权限设计，请问有什么理论依据？感觉很像ecshop的权限设计，谢谢！
如果想脑补一下权限设计的知识，有哪些资料和书籍推荐的？

敬谢！
