### ISSUE TITLE
php artisan db:init报错

### ISSUE THREAD

**Issue by raomingchao** [ForoneTech/ForoneAdmin#4]
已经按照流程添加Provider,Forone\Admin\Providers\ForoneServiceProvider::class
![image](https://cloud.githubusercontent.com/assets/7949453/9033881/ee97298c-39fd-11e5-986f-aa0503ed82c1.png)

**Comment by mani95lisa** [comment]
@raomingchao 你有运行 `composer dump-autoload`吗

**Comment by yangyugang** [comment]
@raomingchao sudo composer update 一下试试

**Comment by raomingchao** [comment]
@mani95lisa @yangyugang 也update过了，还是会报错了

➜ laravel5.1  composer dump-autoload
Generating autoload files
➜  laravel5.1  php artisan db:init  
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Forone\Admin\Providers\ForoneServiceProvider' not found  

再不行，我再重新安装一次看看了，感谢~

**Comment by sword-jin** [comment]
@raomingchao 你这个报错很奇怪啊，没道理啊

**Comment by raomingchao** [comment]
@yangyugang ·sudo composer update·可以了，不加·sudo·不行，也没什么提示，有点奇怪了

**Comment by yangyugang** [comment]
@raomingchao 没有加sudo，在写文件的时候，可能会没有权限，我一般都会加上sudo的
