### ISSUE TITLE
执行php artisan db:init 会报错

### ISSUE THREAD

**Issue by yanqing6628780** [ForoneTech/ForoneAdmin#5]
执行 php artisan db:init 
![qq 20150813164929](https://cloud.githubusercontent.com/assets/8479740/9246009/480dbe10-41db-11e5-9677-a4cd2685863a.png)

我的数据库是没有这个roles表的。。。你上面也执行了drop table然后table created successfully了。但是，现在又报错说表已存在。

**Comment by mani95lisa** [comment]
@yanqing6628780 重构了下项目，使用了新的地址，请访问 https://github.com/ForoneTech/ForoneAdministrator  使用新的命令不会再有这样的问题了
