### ISSUE TITLE
执行php artisan db:update时提示"Class AdminsTableSeeder does not exist"

### ISSUE THREAD

**Issue by zhengxing09** [ForoneTech/ForoneAdmin#6]
最后执行update的时候总是提示 Class AdminsTableSeeder does not exist，但是文件实际上是存在的。
![2015-08-16 20 38 15](https://cloud.githubusercontent.com/assets/7546664/9293271/c3c29c88-4456-11e5-9000-8a0b957055d7.png)

**Comment by mani95lisa** [comment]
这个需要运行下 `composer dump-autoload`把刚生成的seeder编译下才行

**Comment by mani95lisa** [comment]
@zhengxing09 重构了下项目，使用了新的库地址，请访问 https://github.com/ForoneTech/ForoneAdministrator
