### ISSUE TITLE
Admin Username and Password

### ISSUE THREAD

**Issue by shineklbm** [ForoneTech/ForoneAdmin#7]
This package looks promising, somehow we are having extreme difficulty with the language. Can you please add the english translation too? Also what is the admin username and password?

**Comment by mani95lisa** [comment]
@shineklbm We have changed this to https://github.com/ForoneTech/ForoneAdministrator, there're many changes so we create new project.

About the english translation we'll add it in the next month. Please give us a new issue in the new project.
For now, maybe you can just follow the english code for test, it's a little busy for us these days.

If you have any other questions please add it in new project.
